(define (sqrt x)
  (define (improve guess)
    (average guess (/ x guess)))
  (define (good_enough? guess)
    (< (abs (- (square guess) x))
       .001))
  (define (try guess)
    (if (good_enough? guess)
      guess
      (try (improve guess))))
  (try 1))
